name: Build, Push Image Google GCR an Publish Portainer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE: "nginx"
  IMAGE_TAG: ${{ github.sha }}
  STACK_NAME: "registry"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{secrets.REGISTRY_HOSTNAME}}/${{env.IMAGE}}:${{env.IMAGE_TAG}},${{secrets.REGISTRY_HOSTNAME}}/${{env.IMAGE}}:latest

    - name: portainer deploy
      uses: LGinC/portainer-stack-deploy@master
      with:
        serverurl: ${{secrets.PORTAINER_HOSTNAME}}
        username: ${{ secrets.PORTAINER_USERNAME }}
        password: ${{ secrets.PORTAINER_PASSWORD }}
        endpointId: ${{ secrets.PORTAINER_ENDPOINT_ID }}
        stackname: ${{env.STACK_NAME}}
        imagenames: |
            ${{secrets.REGISTRY_HOSTNAME}}/${{env.IMAGE}}:latest
        env: |
          ${{secrets.PORTAINER_ENV}}
        docker_compose_path: docker-compose.yaml