name: Build, Push Image Google GCR an Publish Portainer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE: "nginx"
  IMAGE_TAG: ${{ github.sha }}
  STACK_NAME: "registry"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GCR
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{secrets.REGISTRY_HOSTNAME}}/${{env.IMAGE}}:${{env.IMAGE_TAG}},${{secrets.REGISTRY_HOSTNAME}}/${{env.IMAGE}}:latest
        
  deploy:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - uses: bots-house/portainer-deploy-stack-action
            with:
              # url of Poratainer instance
              portainer-url: ${{ secrets.PORTAINER_HOSTNAME }}

              # portainer auth
              portainer-username: ${{ secrets.PORTAINER_USERNAME }}
              portainer-password: ${{ secrets.PORTAINER_PASSWORD }}
              
              # internal portainer cluster id
              portainer-endpoint: PORTAINER_ENDPOINT_ID
              
              # stack name
              stack-name: ${{env.STACK_NAME}}

              # docker stack file location
              stack-file: docker-compose.yml
              
              # vars to substitute in stack
              stack-vars: |
                ${{secrets.PORTAINER_ENV}}